### ISSUE TITLE
Set up toaster where the old one used to be

### ISSUE THREAD

**Issue by sherigilland** [sherigilland/To-Do#7]

**Comment by damengilland** [comment]
@sherigilland Note how I assigned this to you, and used the label "ready for review."  Try attaching a photo here and we can call it done.

**Comment by sherigilland** [comment]
![done](https://cloud.githubusercontent.com/assets/13260418/8607453/82f8acf4-2658-11e5-9483-da4ea2f08107.jpg)

**Comment by damengilland** [comment]
Photo of the oven in the right place.
